http:
  public_base: "https://matrix-auth.{{DOMAIN}}/"
  issuer: "https://matrix-auth.{{DOMAIN}}/"
  listeners:
    - name: web
      resources:
        - name: discovery
        - name: human
        - name: oauth
        - name: compat
        - name: graphql
        - name: assets
        - name: health
      binds:
        - host: 0.0.0.0
          port: 8080

database:
  host: postgres
  port: 5432
  username: matrix_authentication_service
  password: "{{POSTGRES_MATRIX_AUTHENTICATION_SERVICE_PASSWORD}}"
  database: matrix_authentication_service
  ssl_mode: disable

matrix:
  homeserver: "matrix.{{DOMAIN}}"
  endpoint: "http://synapse:8008"
  secret: "{{MATRIX_AUTHENTICATION_SERVICE_SHARED_SECRET}}"

secrets:
  encryption: "{{MATRIX_AUTHENTICATION_SERVICE_ENCRYPTION_SECRET}}"
  keys:
    - key_file: /keys/rsa.pem

passwords:
  enabled: false
  schemes:
    - version: 1
      algorithm: bcrypt

account:
  email_change_allowed: true
  displayname_change_allowed: true
  password_registration_enabled: false
  password_recovery_enabled: false
  login_with_email_allowed: false

upstream_oauth2:
  providers:
    - id: "{{MATRIX_AUTHENTICATION_SERVICE_UPSTREAM_PROVIDER_ID}}"
      synapse_idp_id: oidc-keycloak
      issuer: "https://keycloak.{{DOMAIN}}/realms/webservices"
      human_name: "Keycloak SSO"
      brand_name: keycloak
      client_id: matrix-authentication-service
      client_secret: "{{MATRIX_AUTHENTICATION_SERVICE_OAUTH_SECRET}}"
      token_endpoint_auth_method: client_secret_post
      scope: "openid email profile"
      discovery_mode: disabled
      authorization_endpoint: "https://keycloak.{{DOMAIN}}/realms/webservices/protocol/openid-connect/auth"
      token_endpoint: "http://keycloak:8080/realms/webservices/protocol/openid-connect/token"
      userinfo_endpoint: "http://keycloak:8080/realms/webservices/protocol/openid-connect/userinfo"
      jwks_uri: "http://keycloak:8080/realms/webservices/protocol/openid-connect/certs"
      fetch_userinfo: true
      claims_imports:
        localpart:
          action: require
          template: "{{ user.preferred_username|default(user.sub, true)|lower }}"
          on_conflict: add
        displayname:
          action: force
          template: "{{ user.name }}"
        email:
          action: force
          template: "{{ user.email }}"

branding:
  service_name: "Datamancy Matrix"
